name: tests
on:
  push:
    branches:
      - main
      - dev
  pull_request: {}

permissions:
  actions: write
  contents: read

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      - name: Check Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze .
      - name: RUn tests and collect coverage
        run: flutter test --coverage
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
